name: Build

on:
  push:
    branches:
      - workflow-test

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x64, x86, arm, arm64]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 4.6.x
          architecture: ${{ matrix.arch }}
      - name: Build the project
        run: dotnet publish -c Release -o publish
      - name: Upload the executable
        uses: actions/upload-artifact@v3
        with:
          name: Release-${{ matrix.arch }}
          path: publish/**/*.exe
